import { isGrounded, raycast, resolveMove, type CollisionWorld } from './collision.js';
import { archetypeByIndex, Brain, type EnemyArchetype } from './enemies.js';
import { eyeOffset } from './movement.js';
import * as fx from './math/fixed.js';
import { nextChance, nextRangeFx } from './math/rng.js';
import { buildTacticalContent, type CoverPointSet, type NavGraph } from './nav.js';
import type { EnemyState, PlayerState, SimState, Vec3Fx } from './state.js';

export interface EnemyEvent { kind: 'telegraph' | 'enemyShot' | 'playerHit'; enemyId: number; damage?: number; }
const ENEMY_SHAPE = { halfWidth: fx.fromRatio(40, 100), height: fx.fromRatio(180, 100) };
const ENEMY_EYE = fx.fromRatio(150, 100);
const GRAVITY = fx.fromRatio(22 * 1000, 60 * 60 * 1000) | 0;
const MAX_FALL = fx.fromRatio(45 * 1000, 60 * 1000);
export const MIN_PLAYER_SEPARATION = fx.fromRatio(110, 100);
const RECOVERY_TICKS = 30;
function distanceSq(a: Vec3Fx, b: Vec3Fx): number { const dx = fx.toFloat((a.x - b.x) | 0); const dz = fx.toFloat((a.z - b.z) | 0); return dx * dx + dz * dz; }
function horizontalDistance(a: Vec3Fx, b: Vec3Fx): fx.Fx { const hi = fx.max(fx.abs((a.x - b.x) | 0), fx.abs((a.z - b.z) | 0)); const lo = fx.min(fx.abs((a.x - b.x) | 0), fx.abs((a.z - b.z) | 0)); return (hi + fx.mul(lo, fx.fromRatio(41, 100))) | 0; }
function hasLineOfSight(world: CollisionWorld, enemy: EnemyState, target: Vec3Fx, range: fx.Fx): boolean { const origin = { x: enemy.pos.x, y: (enemy.pos.y + ENEMY_EYE) | 0, z: enemy.pos.z }; const dx = (target.x - origin.x) | 0, dy = (target.y - origin.y) | 0, dz = (target.z - origin.z) | 0; const dist = horizontalDistance(target, origin); if (dist > range) return false; if (dist === 0) return true; const dir = { x: fx.div(dx, dist), y: fx.div(dy, dist), z: fx.div(dz, dist) }; const hit = raycast(world, origin, dir, dist); return hit === null || hit.distance >= dist - fx.fromRatio(10, 100); }
function moveToward(world: CollisionWorld, enemy: EnemyState, x: fx.Fx, z: fx.Fx, speed: fx.Fx): boolean { const dx = (x - enemy.pos.x) | 0, dz = (z - enemy.pos.z) | 0; const dist = horizontalDistance({ x, y: 0, z }, enemy.pos); if (dist > fx.fromRatio(5, 100)) { enemy.vel.x = fx.mul(fx.div(dx, dist), speed); enemy.vel.z = fx.mul(fx.div(dz, dist), speed); enemy.yaw = fx.atan2Turns(dx, dz); } else { enemy.vel.x = 0; enemy.vel.z = 0; } if (isGrounded(world, enemy.pos, ENEMY_SHAPE)) { if (enemy.vel.y < 0) enemy.vel.y = 0; } else enemy.vel.y = fx.max((enemy.vel.y - GRAVITY) | 0, -MAX_FALL | 0); const r = resolveMove(world, enemy.pos, ENEMY_SHAPE, { x: enemy.vel.x, y: enemy.vel.y, z: enemy.vel.z }, true); enemy.pos = r.pos; if (r.hitX) enemy.vel.x = 0; if (r.hitZ) enemy.vel.z = 0; if (r.hitY) enemy.vel.y = 0; return r.hitX || r.hitZ; }
function separate(enemy: EnemyState, player: PlayerState): void { const dx = (enemy.pos.x - player.pos.x) | 0, dz = (enemy.pos.z - player.pos.z) | 0, d = fx.length2(dx, dz); if (d >= MIN_PLAYER_SEPARATION) return; if (d === 0) enemy.pos.x = (player.pos.x + MIN_PLAYER_SEPARATION) | 0; else { const k = fx.div(MIN_PLAYER_SEPARATION, d); enemy.pos.x = (player.pos.x + fx.mul(dx, k)) | 0; enemy.pos.z = (player.pos.z + fx.mul(dz, k)) | 0; } enemy.vel.x = 0; enemy.vel.z = 0; }
function face(enemy: EnemyState, target: Vec3Fx): void { enemy.yaw = fx.atan2Turns((target.x - enemy.pos.x) | 0, (target.z - enemy.pos.z) | 0); }
function fire(state: SimState, enemy: EnemyState, def: EnemyArchetype, distance: fx.Fx, events: EnemyEvent[]): void { if (state.player.downTicks > 0 || enemy.reactionTicks > 0) return; if (enemy.telegraphing === 1) { if (enemy.brainTicks > 0) return; enemy.telegraphing = 0; enemy.fireCooldownTicks = def.fireIntervalTicks; events.push({ kind: 'enemyShot', enemyId: enemy.id }); const scale = fx.clamp(fx.div((def.sightRange - distance) | 0, def.sightRange), fx.fromRatio(30, 100), fx.FX_ONE); if (nextChance(state.rngAi, fx.mul(def.accuracy, scale))) { const p = state.player; p.health = (p.health - def.damage) | 0; events.push({ kind: 'playerHit', enemyId: enemy.id, damage: fx.toInt(def.damage) }); if (p.health <= 0) { p.health = 0; p.deaths += 1; p.downTicks = 180; } } return; } if (enemy.fireCooldownTicks > 0) return; enemy.telegraphing = 1; enemy.brainTicks = def.telegraphTicks; events.push({ kind: 'telegraph', enemyId: enemy.id }); }
function coverTarget(covers: CoverPointSet, world: CollisionWorld, enemy: EnemyState, player: Vec3Fx): Vec3Fx | null { const occupied = covers.select(world, enemy.pos, player, []); return occupied?.pos ?? null; }

/** Tactical enemy step. Existing state fields carry the route node and bounded recovery timer. */
export function stepEnemies(state: SimState, world: CollisionWorld): EnemyEvent[] {
  const events: EnemyEvent[] = []; if (!state.enemies.length) return events; const p = state.player; const eye = { x: p.pos.x, y: (p.pos.y + eyeOffset(p.crouching === 1)) | 0, z: p.pos.z }; const tactical = buildTacticalContent(world, [p.pos, ...state.enemies.map((e) => e.pos)]); const graph: NavGraph = tactical.graph;
  for (const enemy of state.enemies) { if (enemy.health <= 0) continue; const def = archetypeByIndex(enemy.archetype); const distance = horizontalDistance(eye, enemy.pos); const visible = p.downTicks === 0 && hasLineOfSight(world, enemy, eye, def.sightRange); const heard = p.downTicks === 0 && distance <= def.sightRange;
    if (visible || heard) { if (enemy.brain === Brain.Idle) { enemy.reactionTicks = def.reactionTicks; enemy.brain = Brain.Advance; enemy.targetNode = graph.nearest(p.pos); } if (enemy.reactionTicks > 0) { face(enemy, eye); separate(enemy, p); continue; }
      const role = enemy.id % 3; let tx = p.pos.x, tz = p.pos.z; if (role === 0) { const cover = coverTarget(tactical.covers, world, enemy, eye); if (cover && distance < fx.fromInt(8)) { enemy.brain = Brain.Retreat; tx = cover.x; tz = cover.z; } } else if (role === 1) { enemy.brain = Brain.Advance; tx = (p.pos.x + fx.fromInt(10)) | 0; tz = (p.pos.z - fx.fromInt(10)) | 0; } else { enemy.brain = distance > def.preferredRange ? Brain.Advance : Brain.Engage; }
      if (enemy.telegraphing === 1) { enemy.vel.x = 0; enemy.vel.z = 0; moveToward(world, enemy, enemy.pos.x, enemy.pos.z, 0); } else if (enemy.brain === Brain.Retreat || distance > def.preferredRange) { const blocked = moveToward(world, enemy, tx, tz, def.speed); if (blocked) { enemy.brainTicks = RECOVERY_TICKS; enemy.targetNode = graph.nearest(enemy.pos); } } else if (distance < fx.div(def.preferredRange, fx.fromInt(2))) { enemy.brain = Brain.Retreat; moveToward(world, enemy, (enemy.pos.x + enemy.pos.x - p.pos.x) | 0, (enemy.pos.z + enemy.pos.z - p.pos.z) | 0, def.speed); } else moveToward(world, enemy, enemy.pos.x, enemy.pos.z, 0); face(enemy, eye); fire(state, enemy, def, distance, events);
    } else if (p.downTicks > 0) { enemy.brain = Brain.Idle; enemy.telegraphing = 0; moveToward(world, enemy, enemy.pos.x, enemy.pos.z, 0); } else { enemy.telegraphing = 0; if (enemy.brain !== Brain.Idle) enemy.brain = Brain.Advance; const jitterX = nextRangeFx(state.rngAi, -fx.fromInt(3), fx.fromInt(3)); const jitterZ = nextRangeFx(state.rngAi, -fx.fromInt(3), fx.fromInt(3)); const blocked = moveToward(world, enemy, (p.pos.x + jitterX) | 0, (p.pos.z + jitterZ) | 0, def.speed); if (blocked) enemy.brainTicks = RECOVERY_TICKS; }
    separate(enemy, p);
  } return events;
}
export function stepRespawn(state: SimState, spawns: readonly Vec3Fx[], maxHealth: fx.Fx): void { const p = state.player; if (p.downTicks !== 1) return; let best = spawns[0]!; let score = -1; for (const spawn of spawns) { let nearest = Number.MAX_SAFE_INTEGER; for (const enemy of state.enemies) if (enemy.health > 0) nearest = Math.min(nearest, distanceSq(spawn, enemy.pos)); if (nearest > score) { score = nearest; best = spawn; } } p.pos = { ...best }; p.vel = { x: 0, y: 0, z: 0 }; p.health = maxHealth; p.spreadBloom = 0; p.recoilPitch = 0; }
