-- RE:Arena operator console (WO-50).
-- Apply with `supabase db push` after reviewing in a staging project.
-- Grant an operator by adding {"role":"operator"} to auth.users.app_metadata,
-- then refresh the user's JWT by signing out and in again (or refreshSession()).

create or replace function public.assert_operator()
returns void
language plpgsql
stable
security definer
set search_path = public, auth
as $$
begin
  if coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') <> 'operator' then
    raise exception 'operator role required' using errcode = '42501';
  end if;
end;
$$;

revoke all on function public.assert_operator() from public;
grant execute on function public.assert_operator() to authenticated;

alter table public.runs add column if not exists device_class text;
comment on column public.runs.device_class is 'Optional client-reported class: desktop, mobile, tablet, or unknown.';

create table if not exists public.verifier_metrics (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.runs(id) on delete cascade,
  sim_version integer not null,
  client_version text not null,
  device_class text not null default 'unknown',
  outcome text not null check (outcome in ('verified', 'rejected')),
  rejection_reason text,
  replay_ms integer,
  first_mismatch_tick integer,
  created_at timestamptz not null default now()
);

create index if not exists verifier_metrics_created_at_idx on public.verifier_metrics(created_at desc);
create index if not exists verifier_metrics_dimensions_idx on public.verifier_metrics(client_version, device_class);

alter table public.verifier_metrics enable row level security;
revoke all on public.verifier_metrics from anon, authenticated;
grant select on public.verifier_metrics to authenticated;

create or replace view public.verifier_rejection_rates as
with dimensions as (
  select client_version, device_class, rejection_reason,
    count(*)::bigint as total,
    count(*) filter (where outcome = 'rejected')::bigint as rejected
  from public.verifier_metrics
  where created_at >= now() - interval '30 days'
  group by client_version, device_class, rejection_reason
)
select client_version, device_class, rejection_reason, total, rejected,
  case when total = 0 then 0::numeric else round(rejected::numeric / total::numeric, 4) end as rate
from dimensions;

revoke all on public.verifier_rejection_rates from public, anon;
grant select on public.verifier_rejection_rates to authenticated;

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  player_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null check (kind in ('run_invalidated', 'player_flagged', 'player_unflagged')),
  run_id uuid references public.runs(id) on delete set null,
  reason text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists notifications_player_created_idx on public.notifications(player_id, created_at desc);
alter table public.notifications enable row level security;
create policy notifications_select_own on public.notifications for select to authenticated using (player_id = auth.uid());
create policy notifications_update_own on public.notifications for update to authenticated using (player_id = auth.uid()) with check (player_id = auth.uid());
revoke insert, delete on public.notifications from anon, authenticated;
grant select, update on public.notifications to authenticated;

audit table if not exists public.operator_audit (
  id bigint generated by default as identity primary key,
  operator_id uuid not null,
  action text not null,
  run_id uuid,
  player_id uuid,
  reason_code text,
  note text,
  created_at timestamptz not null default now()
);

alter table public.operator_audit enable row level security;
revoke all on public.operator_audit from public, anon, authenticated;

create or replace function public.invalidate_run(run_id uuid, reason_code text)
returns jsonb language plpgsql security definer set search_path = public, auth as $$
declare v_player uuid; v_changed boolean;
begin
  perform public.assert_operator();
  if nullif(trim(reason_code), '') is null then raise exception 'reason required'; end if;
  update public.runs set status = 'invalidated' where id = invalidate_run.run_id and status = 'verified' returning player_id into v_player;
  v_changed := found;
  if v_changed then
    delete from public.leaderboard_entries where public.leaderboard_entries.run_id = invalidate_run.run_id;
    delete from public.ghosts where public.ghosts.run_id = invalidate_run.run_id;
    insert into public.notifications(player_id, kind, run_id, reason) values (v_player, 'run_invalidated', invalidate_run.run_id, 'Your verified run was removed after a fair-play review: ' || reason_code);
  end if;
  insert into public.operator_audit(operator_id, action, run_id, player_id, reason_code) values (auth.uid(), 'invalidate_run', invalidate_run.run_id, v_player, reason_code);
  return jsonb_build_object('changed', v_changed, 'run_id', invalidate_run.run_id);
end;
$$;

create or replace function public.set_player_flag(player_id uuid, on boolean, note text default null)
returns jsonb language plpgsql security definer set search_path = public, auth as $$
declare v_changed boolean;
begin
  perform public.assert_operator();
  if on then
    update public.profiles set flagged_at = coalesce(flagged_at, now()) where id = set_player_flag.player_id;
    v_changed := found;
    if v_changed then insert into public.notifications(player_id, kind, reason) values (set_player_flag.player_id, 'player_flagged', coalesce(note, 'Your entries are under review.')); end if;
  else
    update public.profiles set flagged_at = null where id = set_player_flag.player_id and flagged_at is not null;
    v_changed := found;
    if v_changed then insert into public.notifications(player_id, kind, reason) values (set_player_flag.player_id, 'player_unflagged', 'Your entries are no longer under review.'); end if;
  end if;
  insert into public.operator_audit(operator_id, action, player_id, note) values (auth.uid(), case when on then 'set_player_flag' else 'clear_player_flag' end, set_player_flag.player_id, note);
  return jsonb_build_object('changed', v_changed, 'player_id', set_player_flag.player_id, 'flagged', on);
end;
$$;

create or replace function public.flag_player(player_id uuid, reason text)
returns jsonb language sql security definer set search_path = public as $$ select public.set_player_flag(player_id, true, reason); $$;
create or replace function public.unflag_player(player_id uuid)
returns jsonb language sql security definer set search_path = public as $$ select public.set_player_flag(player_id, false, null); $$;

grant execute on function public.invalidate_run(uuid, text), public.set_player_flag(uuid, boolean, text), public.flag_player(uuid, text), public.unflag_player(uuid) to authenticated;

create or replace function public.get_my_notifications(limit_count integer default 20)
returns setof public.notifications language sql stable security definer set search_path = public as $$
  select * from public.notifications where player_id = auth.uid() order by created_at desc limit greatest(1, least(limit_count, 100));
$$;

create or replace function public.mark_read(notification_id uuid)
returns boolean language sql security definer set search_path = public as $$
  update public.notifications set read_at = coalesce(read_at, now()) where id = mark_read.notification_id and player_id = auth.uid() returning true;
$$;

grant execute on function public.get_my_notifications(integer), public.mark_read(uuid) to authenticated;
comment on function public.assert_operator() is 'Operator JWT grant: update auth.users.app_metadata with {"role":"operator"}, then refresh the JWT.';
